### ISSUE TITLE
Export not working

### ISSUE THREAD

**Issue by oripka** [realazthat/excalidraw-brute-export-cli#1]
I get this error with the code from npm and git

```
npx excalidraw-brute-export-cli -i ../slides/cysec/public/cysec/drawings/bitbattack.excalidraw -s 1 -f svg -o bla.svg -v
console.log('amain')
info: logger.info('amain')
info: options:
info: {
  i: '../slides/cysec/public/cysec/drawings/bitbattack.excalidraw',
  input: '../slides/cysec/public/cysec/drawings/bitbattack.excalidraw',
  s: 1,
  scale: 1,
  f: 'svg',
  format: 'svg',
  o: 'bla.svg',
  output: 'bla.svg',
  v: true,
  background: false,
  darkMode: false,
  embedScene: false,
  url: 'https://excalidraw.com/',
  headless: true,
  screenshots: ''
}
info: OK file is chosen?


info: [JavaScript Warning: "The resource at “https://excalidraw.com/Virgil.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly." {file: "https://excalidraw.com/" line: 0}]
info: [JavaScript Warning: "The resource at “https://excalidraw.com/Cascadia.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly." {file: "https://excalidraw.com/" line: 0}]

error: Error: page.waitForEvent: Timeout 30000ms exceeded while waiting for event "filechooser"
       =========================== logs ===========================
       waiting for event "filechooser"
       ============================================================
       error: {
         name: 'TimeoutError',
         stack: 'page.waitForEvent: Timeout 30000ms exceeded while waiting for event "filechooser"\n' 

```

**Comment by realazthat** [comment]
Ah yeah timeouts can happen sometimes, either because the page didn't load, or something is taking too long.

* I will add a flag to raise the timeout length (https://github.com/realazthat/excalidraw-brute-export-cli/issues/2).
* Are you able to share the diagram file?
* If you can reproduce this, try to enable screenshots e.g `--screenshots ./screenshots` and see what it got stuck on.

**Comment by realazthat** [comment]
I enabled --timeout milliseconds in 50c6f8d. I am not sure increasing the timeout will help though.

**Comment by realazthat** [comment]
One more thing you can try is to use `--headless false`. In 26dd98e, I've added `--leave-browser-running`, which if set to `true` will leave the head-full browser running after a crash so you can see what is happening. I've also added an option `--action-sleep-time` which lets you set the delay between each action so it doesn't all happen instantly.

Also this might be the source of the error: too small of a delay (it defaults to 100ms).

**Comment by oripka** [comment]
Thanks for your quick response. I realized that this probably only works on Windows / Linux. I am running it on macOS, using the Meta key instead of Control makes it work. The screenshot hint made me realized it did not even open the file

```
    await page.keyboard.press("Meta+O");
[...]
    await page.keyboard.press("Meta+Shift+E");
```
